### ISSUE TITLE
fix for arduino-cli github action

### ISSUE THREAD

**Issue by joshua-8** [ChanceCuddeback/ArduinoBlinkCI#1]
Dear @ChanceCuddeback,
Please pardon my intrusion on your project, but I saw your message [here](https://github.com/arduino/setup-arduino-cli/pull/48#issuecomment-1520604339) and I understand the pain of trying to get github actions running.

I think the reason your action is failing is because the arduino-platform and fqbn variables in your matrix are not being fed to arduino-cli. 

With the following fix https://github.com/joshua-8/ArduinoBlinkCI/commit/307e92bb05ef9b8a9a20172e37465eb42a743913 the action completed on my fork of your project https://github.com/joshua-8/ArduinoBlinkCI/actions/runs/4789769883.

Best of luck with all your projects!

-joshua-8

**Comment by ChanceCuddeback** [comment]
@joshua-8 Thank you!!
